// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAidOozvrft71PDb6vNfzBOsZnluSWdgS0',
    appId: '1:976416238131:web:8d12f08bbb9892fe34d146',
    messagingSenderId: '976416238131',
    projectId: 'authentication-c9d6f',
    authDomain: 'authentication-c9d6f.firebaseapp.com',
    storageBucket: 'authentication-c9d6f.appspot.com',
    measurementId: 'G-851HLX8466',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClnTozJZG9-lztH7i-OgK9qb65LJDgwxY',
    appId: '1:976416238131:android:811f07b531c6407734d146',
    messagingSenderId: '976416238131',
    projectId: 'authentication-c9d6f',
    storageBucket: 'authentication-c9d6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnIvM3KkKT1Msc4A6tnbOy616zwZYcb3Y',
    appId: '1:976416238131:ios:421aafb4a92e8a6c34d146',
    messagingSenderId: '976416238131',
    projectId: 'authentication-c9d6f',
    storageBucket: 'authentication-c9d6f.appspot.com',
    iosBundleId: 'com.user.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnIvM3KkKT1Msc4A6tnbOy616zwZYcb3Y',
    appId: '1:976416238131:ios:421aafb4a92e8a6c34d146',
    messagingSenderId: '976416238131',
    projectId: 'authentication-c9d6f',
    storageBucket: 'authentication-c9d6f.appspot.com',
    iosBundleId: 'com.user.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAidOozvrft71PDb6vNfzBOsZnluSWdgS0',
    appId: '1:976416238131:web:16f6fe09fa31d88f34d146',
    messagingSenderId: '976416238131',
    projectId: 'authentication-c9d6f',
    authDomain: 'authentication-c9d6f.firebaseapp.com',
    storageBucket: 'authentication-c9d6f.appspot.com',
    measurementId: 'G-TGZRMGK7LL',
  );
}
